pluginManagement {
  repositories {
    maven {
      credentials {
        username "$rbArtifactoryUser"
        password "$rbArtifactoryPassword"
      }
      url "https://rb-artifactory.bosch.com/artifactory/gradle-plugins-remote-cache/"
    }
    maven {
      credentials {
        username "$rbArtifactoryUser"
        password "$rbArtifactoryPassword"
      }
      url "https://rb-artifactory.bosch.com/artifactory/maven-central-remote/"
    }

    maven {
      credentials {
        username "$rbArtifactoryUser"
        password "$rbArtifactoryPassword"
      }
      url = "https://rb-artifactory.bosch.com/artifactory/bhp-eat-spexjava-local/"
    }

    mavenLocal()
  }
  plugins {
    id 'bosch.bh.spex.gradle.spex-testprogram' version '1.10.0'
  }
}

rootProject.name = 'ivtb-example-project'
