"tlc2" {
  app.branch.name="master"
  app.version="1.15.0"
  app.commit.hash="ac60198e77cdd78b7fc868e77371906758ccbc88"
  app.is.repo.clean=false
  app.is.on.tag=true
  app.build.date="2025-11-27T07:51:17.370+0000"
  app.commit.date="Nov 27 2025, 06:43:41"
}

"spex-test-platform" {
  app.branch.name="master"
  app.version="1.2.4"
  app.commit.hash="1a0123a60f9824989eedccdf961ad7e5e57235d6"
  app.is.repo.clean=false
  app.is.on.tag=true
  app.build.date="2026-04-24T11:23:29.801+0000"
  app.commit.date="Apr 24 2026, 11:12:50"
}

"spex-tl-sdk" {
  app.branch.name="master"
  app.version="1.14.1"
  app.commit.hash="d449946d2efbebc99b05f9ebfe59afd07e526b6c"
  app.is.repo.clean=false
  app.is.on.tag=true
  app.build.date="2025-07-28T11:44:59.350+0000"
  app.commit.date="Jul 28 2025, 11:23:53"
}

"recrealtimelib" {
  app.branch.name="master"
  app.version="1.4.3"
  app.commit.hash="365d24b96d3705b3b502a4ec516b539558913c87"
  app.is.repo.clean=false
  app.is.on.tag=true
  app.build.date="2025-09-26T07:25:47.886+0000"
  app.commit.date="Sep 26 2025, 07:21:17"
}

"baselib" {
  app.branch.name="master"
  app.version="2.5.1"
  app.commit.hash="90e6eeb4765b4284754fb8f606a72dd9f3648726"
  app.is.repo.clean=false
  app.is.on.tag=true
  app.build.date="2026-04-29T05:58:25.708+0000"
  app.commit.date="Apr 29 2026, 05:53:12"
}

"ivtb-example-project" {
  app.branch.name="refs/heads/feature/improved-stepReturn-handling"
  app.version="0.0.1-SNAPSHOT"
  app.commit.hash="4024c8800ebc1a2694803f859ea6d02de49ae62d"
  app.is.repo.clean=false
  app.is.on.tag=false
  app.build.date="2026-04-29T13:30:05.972+0200"
  app.commit.date="Apr 27 2026, 10:35:14"
}

